### PR TITLE
Fixes #25 for run-pylint.sh

### LINKED ISSUE #25: run-pylint.sh in docker image fails
- Skip double testing files.
- The installed pylint causes some errors.
- For "commited files" check the current working path  `/capstone/ros$ ../run-pylint.sh upstream/master`
- Adjust the .pylintrc path based on the location of the script.

### PR DESCRIPTION
**Pull request by avrabe**
Scan each file only once.
Reinstall pylint while in docker.
Use always the .pylintrc file.
Be aware of the current working path

Signed-off-by: Ralf Anton Beier <ralf_beier@me.com>

### CODE REVIEW

File: run-pylint.sh [hunk 1]
```diff
@@ -9,15 +9,33 @@ while getopts "h" arg; do
...
 then
-    echo "###### check: $1 (origin: $2)"
-    pylint --output-format=parseable --rcfile=._pylintrc $1
+    echo "###### check: $1"
+    pylint --output-format=parseable --rcfile=$SCRIPTPATH/.pylintrc "$1"
 fi
 }
 
+function _write {
+file=$(readlink -e "$1")
```
Comment (asimonov) [inline run-pylint.sh]: can you indent this block?

File: run-pylint.sh [hunk 2]
```diff
@@ -9,15 +9,33 @@ while getopts "h" arg; do
...
+echo "$file" >> $LOCKFILE
+}
+
+if running_in_docker
+then
+pip install pylint > /dev/null
```
Comment (asimonov) [inline run-pylint.sh]: and indent this

**Review by asimonov — APPROVED** [review]
apart from the indentation I am happy. mainly because I understand little of what is going on now in this shell script :)

**Review by asimonov — APPROVED** [review]
